# Generated by Django 5.1.3 on 2024-12-01 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id_dis', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dis', models.CharField(max_length=50)),
                ('tel_dis', models.BigIntegerField(blank=True, null=True)),
                ('dir_dis', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_emp', models.CharField(max_length=50)),
                ('pue_emp', models.CharField(max_length=30)),
                ('fec_emp', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=20)),
                ('des_pro', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_pro', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDistribuidor',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('fec_ord', models.DateField(blank=True, null=True)),
                ('est_ord', models.CharField(blank=True, max_length=20, null=True)),
                ('id_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.distribuidor')),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('fec_inv', models.DateField()),
                ('can_inv', models.IntegerField()),
                ('ubi_inv', models.CharField(blank=True, max_length=100, null=True)),
                ('id_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_det', models.AutoField(primary_key=True, serialize=False)),
                ('can_pro', models.IntegerField()),
                ('pre_uni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.ordendistribuidor')),
                ('id_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_db.producto')),
            ],
        ),
    ]
